name: Test
on: [push, pull_request]
jobs:
  ubuntu2204-gpp:
    strategy:
      matrix:
        os: [ubuntu-22.04]
        compiler: [g++]
        version: [9, 10, 11, 12]
    name: Use ${{ matrix.compiler }}-${{ matrix.version }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - run: g++-${{ matrix.version }} -std=c++17 -Wall -Wextra -Wpedantic -Werror -O2 -fsanitize=address,undefined,pointer-compare,pointer-subtract test/validate.cpp -o validate
      - run: ./validate
  ubuntu2004-gpp:
    strategy:
      matrix:
        os: [ubuntu-20.04]
        compiler: [g++]
        version: [9, 10]
    name: Use ${{ matrix.compiler }}-${{ matrix.version }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - run: g++-${{ matrix.version }} -std=c++17 -Wall -Wextra -Wpedantic -Werror -O2 -fsanitize=address,undefined,pointer-compare,pointer-subtract test/validate.cpp -o validate
      - run: ./validate
